version: '3.1'

volumes:
  pg_vol:

services:
  db:
    image: postgres:11.2-alpine
    volumes:
      - pg_vol:/var/lib/postgresql/data
    expose:
    - "5432"
    environment:
      POSTGRES_DB: todo_web
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
